name: test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install clippy and rustfmt
        run: rustup component add clippy rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Ruff
        run: pipx run ruff check
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Clippy (pure rust)
        run: cargo clippy --tests -- -D warnings
      - name: Clippy (pyo3)
        run: cargo clippy --tests --all-features -- -D warnings

  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
